### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by Hanmingsan** [NanKeRen2020/UVR5_Linux#3]
i have compeletely followed the instructions, however i can not use the application and i have got this:

(uvr5) hanmingsan@sonetto:~/Desktop/UVR5_Linux$ python UVR.py
Traceback (most recent call last):
  File "/home/hanmingsan/Desktop/UVR5_Linux/UVR.py", line 6298, in <module>
    root = MainWindow()
  File "/home/hanmingsan/Desktop/UVR5_Linux/UVR.py", line 560, in __init__
    self.logo_img = open_image(path=banner_path,
  File "/home/hanmingsan/Desktop/UVR5_Linux/UVR.py", line 399, in open_image
    img = img.resize((size[0], int(size[0] * ratio)), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

BTW i am using conda

**Comment by 641i130** [comment]
I have the same error. Also using conda.

This solution fixed it for me.

https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias

Just find and replace all the `Image.ANTIALIAS` -> `Image.Resampling.LANCZOS`.
